- name: update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: uninstall bind
  apt: name=bind9 state=absent

- name: install deps
  apt: name=dnsmasq state=installed

- name: ensure configure directory
  file:
    dest: /etc/dnsmasq.d
    state: directory

- name: ensure dnsmasq configuration
  template:
    dest: /etc/dnsmasq.conf
    src: dnsmasq.conf.j2
  notify:
    - restart dnsmasq

- name: ensure configure directory
  file:
    dest: /etc/resolvconf/resolv.conf.d
    state: directory

- name: add local dns lookup
  lineinfile:
    insertbefore: BOF
    state: present
    line: "nameserver 127.0.0.1"
    dest: "/etc/resolvconf/resolv.conf.d/consul"
    create: yes

- name: create alternate upstream servers file for dnsmasq
  template:
    src: "{{ consul_dnsmasq_upstream_template }}"
    dest: /etc/resolv_dnsmasq.conf
  when: "{{ (consul_dnsmasq.upstream_servers is defined) and consul_dnsmasq.upstream_servers }}"
  notify:
    - restart dnsmasq

