---

- name: install consul
  include: install.yml
- { name: install consul ui, include: install-ui.yml, when: consul_is_ui == true }
- { name: install dnsmasq, include: dnsmasq.yml, when: consul_install_dnsmasq == true }
- name: service restart & enables
  include: service.yml
